name: dart_reactivity_benchmark
description: Benchmark comparing different standalone Dart reactivity/signals frameworks.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  alien_signals: ^0.0.4
  solidart: ^2.0.0-dev.3
  signals_core: ^6.0.2
  preact_signals: ^1.8.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
